name: Cypress Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install
      - name: Instalar Cypress
        uses: cypress-io/github-action@v6
        with:
          install: true
          runTests: true
      - name: Executar Cypress com Mochawesome
        run: npx cypress run
      - name: Salvar artefatos do relatório
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
